tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

brew "python"
brew "awscli"
brew "bash"
brew "coreutils"
brew "curl"
brew "diff-so-fancy"
brew "dnscontrol"
brew "ffmpeg"
brew "findutils"
brew "gh"
brew "git"
brew "git-extras"
brew "git-lfs"
brew "gnu-sed"
brew "go"
brew "grep"
brew "htop"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "moreutils"
brew "neovim"
brew "node"
brew "openssh"
brew "pv"
brew "pyenv"
brew "reattach-to-user-namespace"
brew "screen"
brew "skaffold"
brew "tmux"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "warrensbox/tap/tfswitch"
cask "1password"
cask "aerial"
cask "audio-hijack"
cask "backblaze"
cask "daisydisk"
cask "dash"
cask "discord"
cask "elmedia-player"
cask "farrago"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "istat-menus"
cask "iterm2"
cask "lepton"
cask "pastebot"
cask "postman"
cask "protonvpn"
cask "pycharm-ce"
cask "sketch"
cask "slack"
cask "soundsource"
cask "spotify"
cask "streamlabs-obs"
cask "sublime-text"
cask "telegram"
cask "transmit"
cask "tweetbot"
cask "visual-studio-code"
cask "webstorm"

mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "Calcbot", id: 931657367
mas "com.pixelmatorteam.pixelmator.x", id: 1289583905
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Poolside FM", id: 1514817810
mas "Things", id: 904280696
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
